# Generated by Django 4.0.4 on 2022-04-20 08:44

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_cliente', models.BooleanField(default=False)),
                ('is_gestor_solicitudes', models.BooleanField(default=False)),
                ('is_servicios_adicionales', models.BooleanField(default=False)),
                ('is_organizador_eventos', models.BooleanField(default=False)),
                ('is_personal_direccion', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=14)),
                ('NIF', models.CharField(max_length=9, unique=True)),
                ('nombre_empresa', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('poblacion', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('telefono_empresa', models.CharField(max_length=14)),
                ('email_empresa', models.EmailField(max_length=254)),
                ('mostrar_servicios', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=100)),
                ('cuerpo', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('capacidad', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_generic', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_stand', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicios_Especiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.evento')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios_Asignados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.cliente')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.evento')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.servicio')),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.stand')),
            ],
        ),
        migrations.CreateModel(
            name='Organizador_Evantos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=14, validators=[main.validator.PhoneValidator])),
                ('NIF', models.CharField(max_length=9, unique=True, validators=[main.validator.NIFValidator])),
                ('ciutat', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Historial_Incidencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.comentario')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.estado')),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.incidencia')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=14, validators=[main.validator.PhoneValidator])),
                ('DNI', models.CharField(max_length=9, unique=True, validators=[main.validator.NIFValidator])),
                ('ciutat', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Elementos_Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.carro')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.servicio')),
            ],
        ),
        migrations.AddField(
            model_name='comentario',
            name='incidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.incidencia'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.sector'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carro',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.cliente'),
        ),
        migrations.AddField(
            model_name='carro',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.evento'),
        ),
        migrations.AddField(
            model_name='carro',
            name='stand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.stand'),
        ),
        migrations.CreateModel(
            name='Assignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PD', 'Pendiente'), ('RC', 'Rechazada'), ('AP', 'Aprovada')], default=('PD', 'Pendiente'), max_length=2)),
                ('comentario', models.CharField(max_length=500, null=True)),
                ('es_valido_por_gestor', models.BooleanField(default=False)),
                ('es_valido_por_organizador_eventos', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.cliente')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.evento')),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.stand')),
            ],
        ),
        migrations.CreateModel(
            name='Evento_Stand_Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stand_size', models.CharField(choices=[('GR', 'Grande'), ('MD', 'Mediano'), ('PQ', 'Pequeño')], max_length=2)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.evento')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.sector')),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.stand')),
            ],
            options={
                'unique_together': {('evento', 'stand', 'sector')},
            },
        ),
    ]
