# Generated by Django 4.0.4 on 2022-05-27 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha_solicitud',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 15, 31, 16, 326861)),
        ),
    ]
