# Generated by Django 4.0.3 on 2022-04-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_cliente_sector_alter_sector_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='NIF',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono_empresa',
            field=models.CharField(max_length=14),
        ),
    ]
