# Generated by Django 4.0.4 on 2022-04-21 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_servicio_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orden_Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.cliente')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.estado_orden')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.evento')),
                ('servicios', models.ManyToManyField(to='main.servicio')),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.stand')),
            ],
        ),
        migrations.RenameModel(
            old_name='Estado',
            new_name='Estado_Incidencia',
        ),
        migrations.DeleteModel(
            name='Servicios_Asignados',
        ),
    ]
