# Generated by Django 4.0.4 on 2022-05-26 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_evento_fecha_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha_solicitud',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 9, 18, 3, 693681)),
        ),
    ]
