# Generated by Django 4.0.3 on 2022-04-12 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_cliente_nif_alter_cliente_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignacion',
            name='es_valido_por_gestor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignacion',
            name='es_valido_por_organizador_eventos',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Servicios_Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.evento')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.sector')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.servicio')),
            ],
        ),
    ]
