# Generated by Django 4.0.4 on 2022-04-21 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_estado_orden_orden_servicios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden_servicios',
            name='servicios',
        ),
        migrations.CreateModel(
            name='Servicios_Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.orden_servicios')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.servicio')),
            ],
        ),
    ]
