# Generated by Django 4.0.4 on 2022-04-21 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_orden_servicios_servicios_servicios_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden_servicios',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.estado_orden'),
        ),
    ]
