# Generated by Django 4.0.3 on 2022-04-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_assignacion_es_valido_por_gestor_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicios_Sector',
            new_name='Servicios_Especiales',
        ),
        migrations.AddField(
            model_name='servicio',
            name='is_generic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
