# Generated by Django 4.0.3 on 2022-04-14 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_servicios_sector_servicios_especiales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios_especiales',
            name='sector',
        ),
    ]
