# Generated by Django 4.0.4 on 2022-04-21 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_orden_servicios_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado_orden',
            name='description',
        ),
        migrations.RemoveField(
            model_name='estado_orden',
            name='is_active',
        ),
    ]
