# Generated by Django 4.0.4 on 2022-04-25 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.validator


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_estado_orden_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='estadoIn',
            field=models.CharField(choices=[('PD', 'Pendiente'), ('EP', 'En progreso'), ('SC', 'Solucionada')], default=('PD', 'Pendiente'), max_length=2),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Servicios_adicionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=14, validators=[main.validator.PhoneValidator])),
                ('NIF', models.CharField(max_length=9, unique=True, validators=[main.validator.NIFValidator])),
                ('ciutat', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gestor_solicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=14, validators=[main.validator.PhoneValidator])),
                ('NIF', models.CharField(max_length=9, unique=True, validators=[main.validator.NIFValidator])),
                ('ciutat', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='incidencia',
            name='gestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.servicios_adicionales'),
        ),
    ]
