# Generated by Django 4.0.3 on 2022-04-19 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_servicio_is_generic_servicio_precio_and_more'),
        ('main', '0007_servicio_precio'),
    ]

    operations = [
    ]
