# Generated by Django 4.0.4 on 2022-04-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_incidencia_estadoin_alter_incidencia_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
