# Generated by Django 4.0.4 on 2022-04-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_elementos_carro'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Elementos_Carro',
            new_name='Servicios_Carro',
        ),
        migrations.AddField(
            model_name='evento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
