# Generated by Django 4.0.3 on 2022-04-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_merge_20220419_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignacion',
            name='es_valido_por_gestor',
        ),
        migrations.RemoveField(
            model_name='assignacion',
            name='es_valido_por_organizador_eventos',
        ),
        migrations.AddField(
            model_name='assignacion',
            name='comentario',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='assignacion',
            name='estado',
            field=models.CharField(choices=[('PD', 'Pendiente'), ('RC', 'Rechazado'), ('AP', 'Aprobado')], default=('PD', 'Pendiente'), max_length=2),
        ),
    ]
