# Generated by Django 4.0.4 on 2022-04-18 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_elementos_carro_servicios_carro_evento_activo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicios_Carro',
            new_name='Servicio_Carro',
        ),
    ]
