# Generated by Django 4.0.3 on 2022-04-21 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_assignacion_es_valido_por_gestor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.cliente')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.evento')),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.stand')),
            ],
        ),
        migrations.AddField(
            model_name='assignacion',
            name='es_valido_por_gestor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignacion',
            name='es_valido_por_organizador_eventos',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Elementos_Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.carro')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.servicio')),
            ],
        ),
    ]
