# Generated by Django 4.0.4 on 2022-04-19 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_servicios_carro_servicio_carro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elementos_Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.cliente')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.evento')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.servicio')),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.stand')),
            ],
        ),
        migrations.DeleteModel(
            name='Servicio_Carro',
        ),
    ]
