# Generated by Django 4.0.4 on 2022-04-19 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_elementos_carro_delete_servicio_carro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementos_carro',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='elementos_carro',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='elementos_carro',
            name='stand',
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.cliente')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.evento')),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.stand')),
            ],
        ),
        migrations.AddField(
            model_name='elementos_carro',
            name='carro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.carro'),
            preserve_default=False,
        ),
    ]
